#!/bin/sh

. /etc/openwrt_release

IEEE_PATH="/sys/class/ieee80211"
THERMAL_PATH="/sys/class/thermal"

get_mtwifi_temp() {
	local flag
	local ifname
	local temp
	local mtwifi_vifs="ra0 rax0 rai0 ray0 rae0 raz0"
	local result=""

	for ifname in $mtwifi_vifs; do
		if [ -f "/sys/class/net/${ifname}/flags" ]; then
			flag="$(cat /sys/class/net/${ifname}/flags)"
			if [ "$((flag & 0x1))" -eq "1" ]; then
				temp="$(iwpriv ${ifname} stat | awk '/CurrentTemperature/ {printf("%d°C", $3)}')"
				[ -z "$result" ] && result="${temp}" || result="${result}/${temp}"
			fi
		fi
	done
	echo ${result:-unknown}
}

case "$DISTRIB_TARGET" in
ipq40xx/*|ipq806x/*)
	wifi_temp="$(awk '{printf("%.1f°C ", $0 / 1000)}' "$IEEE_PATH"/phy*/device/hwmon/hwmon*/temp1_input 2>"/dev/null" | awk '$1=$1')"
	;;
mediatek/mt7622)
	wifi_temp="$(awk '{printf("%.1f°C ", $0 / 1000)}' "$IEEE_PATH"/wl*/hwmon*/temp1_input 2>"/dev/null" | awk '$1=$1')"
	;;
mediatek/filogic)
	wifi_temp="$(get_mtwifi_temp)"
	;;
*)
	wifi_temp="$(awk '{printf("%.1f°C ", $0 / 1000)}' "$IEEE_PATH"/phy*/hwmon*/temp1_input 2>"/dev/null" | awk '$1=$1')"
	;;
esac

case "$DISTRIB_TARGET" in
ipq40xx/*)
	if [ -e "$IEEE_PATH/phy0/hwmon0/temp1_input" ]; then
		mt76_temp="$(awk -F ': ' '{print $2}' "$IEEE_PATH/phy0/hwmon0/temp1_input" 2>"/dev/null")°C"
	fi
	[ -z "$mt76_temp" ] || wifi_temp="${wifi_temp:+$wifi_temp }$mt76_temp"
	;;
*)
	cpu_temp="$(awk '{printf("%.1f°C", $0 / 1000)}' "$THERMAL_PATH/thermal_zone0/temp" 2>"/dev/null")"
	;;
esac
# Optimized output logic: ignore WiFi if it's "unknown" or empty
if [ -n "$cpu_temp" ]; then
	if [ -n "$wifi_temp" ] && [ "$wifi_temp" != "unknown" ]; then
		echo -n "CPU: $cpu_temp, WiFi: $wifi_temp"
	else
		echo -n "CPU: $cpu_temp"
	fi
elif [ -n "$wifi_temp" ] && [ "$wifi_temp" != "unknown" ]; then
	echo -n "WiFi: $wifi_temp"
else
	echo -n " "
fi
